name: CI
on: push
jobs:
  test:
    env:
      NODE_ENV: development
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: |
          npm install -g codecov
          npm install
          npm test
          codecov
